<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260307164608 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE virtual_tours (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE virtual_tours_artwork (virtual_tours_id INT NOT NULL, artwork_id INT NOT NULL, PRIMARY KEY (virtual_tours_id, artwork_id))');
        $this->addSql('CREATE INDEX IDX_FA88A46035CE870 ON virtual_tours_artwork (virtual_tours_id)');
        $this->addSql('CREATE INDEX IDX_FA88A460DB8FFA4 ON virtual_tours_artwork (artwork_id)');
        $this->addSql('ALTER TABLE virtual_tours_artwork ADD CONSTRAINT FK_FA88A46035CE870 FOREIGN KEY (virtual_tours_id) REFERENCES virtual_tours (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE virtual_tours_artwork ADD CONSTRAINT FK_FA88A460DB8FFA4 FOREIGN KEY (artwork_id) REFERENCES artwork (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE virtual_tours_artwork DROP CONSTRAINT FK_FA88A46035CE870');
        $this->addSql('ALTER TABLE virtual_tours_artwork DROP CONSTRAINT FK_FA88A460DB8FFA4');
        $this->addSql('DROP TABLE virtual_tours');
        $this->addSql('DROP TABLE virtual_tours_artwork');
    }
}
